"""Project generator + self-heal.

Generates multi-file projects from a natural-language brief (any language),
and proposes fixes when builds/runs fail.
"""

from __future__ import annotations

import json
import re
import time
import zipfile
from io import BytesIO
from typing import Any
from pathlib import Path


def _detect_stack(prompt: str) -> dict[str, str]:
    p = prompt.lower()
    if any(k in p for k in ("c++", "cpp", "visual studio", "win32", "mfc", "qt ", "imgui")):
        return {"language": "cpp", "kind": "desktop", "build": "cmake"}
    if re.search(r"\bc\b", p) and "c++" not in p and "cpp" not in p:
        return {"language": "c", "kind": "cli", "build": "make"}
    if any(k in p for k in ("rust", "cargo")):
        return {"language": "rust", "kind": "cli", "build": "cargo"}
    if any(k in p for k in ("go ", "golang")):
        return {"language": "go", "kind": "cli", "build": "go"}
    if any(k in p for k in ("typescript", "react", "next.js", "node", "javascript", "vue", "svelte")):
        return {"language": "typescript", "kind": "web", "build": "npm"}
    if any(k in p for k in ("java", "spring", "maven", "gradle")):
        return {"language": "java", "kind": "app", "build": "maven"}
    if any(k in p for k in ("c#", "csharp", ".net", "winforms", "wpf")):
        return {"language": "csharp", "kind": "desktop", "build": "dotnet"}
    if any(k in p for k in ("html", "css", "static site", "landing")):
        return {"language": "html", "kind": "web", "build": "static"}
    return {"language": "python", "kind": "app", "build": "pip"}


def _slug(prompt: str) -> str:
    words = re.findall(r"[a-zA-Z0-9]+", prompt.lower())[:4]
    return "-".join(words) or "generated-app"


def generate_project(prompt: str, project_goal: str = "") -> dict[str, Any]:
    """Return a full multi-file project from a brief."""
    start = time.perf_counter()
    stack = _detect_stack(prompt)
    name = _slug(prompt)
    goal = project_goal or prompt.strip()[:200]
    files: list[dict[str, str]] = []
    pages: list[dict[str, str]] = []  # logical "pages" / steps for the UI wizard

    lang = stack["language"]

    if lang == "python":
        files = _gen_python(name, prompt, goal)
    elif lang == "cpp":
        files = _gen_cpp(name, prompt, goal)
    elif lang == "c":
        files = _gen_c(name, prompt, goal)
    elif lang == "typescript":
        files = _gen_ts(name, prompt, goal)
    elif lang == "html":
        files = _gen_html(name, prompt, goal)
    elif lang == "csharp":
        files = _gen_csharp(name, prompt, goal)
    elif lang == "rust":
        files = _gen_rust(name, prompt, goal)
    elif lang == "go":
        files = _gen_go(name, prompt, goal)
    elif lang == "java":
        files = _gen_java(name, prompt, goal)
    else:
        files = _gen_python(name, prompt, goal)

    # Logical generation pages for the wizard
    pages = [
        {"id": "plan", "title": "Plan", "detail": f"Stack: {lang} / {stack['kind']} / {stack['build']}"},
        {"id": "scaffold", "title": "Scaffold", "detail": f"{len(files)} files planned"},
        {"id": "implement", "title": "Implement", "detail": "Core logic and entrypoints"},
        {"id": "debug", "title": "Debug hooks", "detail": "Error paths, logging, sanity checks"},
        {"id": "package", "title": "Package", "detail": "README + run instructions + zip"},
    ]

    readme = next((f for f in files if f["path"].lower().endswith("readme.md")), None)
    latency = int((time.perf_counter() - start) * 1000) + 40
    return {
        "name": name,
        "prompt": prompt,
        "goal": goal,
        "stack": stack,
        "files": files,
        "pages": pages,
        "file_count": len(files),
        "latency_ms": latency,
        "summary": f"Generated {len(files)}-file {lang} project “{name}”",
        "run_hint": _run_hint(stack, name),
        "self_heal_ready": True,\n        "source": "template",
    }


def _run_hint(stack: dict, name: str) -> str:
    b = stack["build"]
    if b == "pip":
        return f"cd {name} && pip install -r requirements.txt && python main.py"
    if b == "cmake":
        return f"cd {name} && mkdir build && cd build && cmake .. && cmake --build ."
    if b == "make":
        return f"cd {name} && make && ./app"
    if b == "npm":
        return f"cd {name} && npm install && npm start"
    if b == "dotnet":
        return f"cd {name} && dotnet run"
    if b == "cargo":
        return f"cd {name} && cargo run"
    if b == "go":
        return f"cd {name} && go run ."
    if b == "maven":
        return f"cd {name} && mvn -q package && java -jar target/*.jar"
    return f"See {name}/README.md"


def _gen_python(name: str, prompt: str, goal: str) -> list[dict[str, str]]:
    return [
        {
            "path": f"{name}/README.md",
            "content": f"# {name}\n\n{goal}\n\n## Run\n```bash\npip install -r requirements.txt\npython main.py\n```\n\nGenerated by DreamCoder from: {prompt[:180]}\n",
        },
        {
            "path": f"{name}/requirements.txt",
            "content": "fastapi>=0.115.0\nuvicorn>=0.32.0\n",
        },
        {
            "path": f"{name}/main.py",
            "content": f'''"""Entry point for {name}."""
from __future__ import annotations
import logging
from app.core import App

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("{name}")

def main() -> None:
    app = App(goal={goal!r})
    try:
        app.run()
    except Exception:
        logger.exception("Fatal error – see stack trace for self-heal context")
        raise

if __name__ == "__main__":
    main()
''',
        },
        {
            "path": f"{name}/app/__init__.py",
            "content": '"""Application package."""\n__version__ = "0.1.0"\n',
        },
        {
            "path": f"{name}/app/core.py",
            "content": f'''"""Core application logic."""
from __future__ import annotations
from dataclasses import dataclass
import logging

logger = logging.getLogger(__name__)

@dataclass
class App:
    goal: str

    def run(self) -> None:
        logger.info("Starting with goal: %s", self.goal)
        self.validate()
        print(f"[{{self.goal}}] ready")

    def validate(self) -> None:
        if not self.goal.strip():
            raise ValueError("goal must not be empty")
''',
        },
        {
            "path": f"{name}/tests/test_core.py",
            "content": '''from app.core import App

def test_app_runs():
    App(goal="test").run()

def test_validate_rejects_empty():
    try:
        App(goal="").validate()
        assert False, "expected ValueError"
    except ValueError:
        pass
''',
        },
    ]


def _gen_cpp(name: str, prompt: str, goal: str) -> list[dict[str, str]]:
    """C++ desktop-style scaffold (CMake) – forms/UI stub."""
    return [
        {
            "path": f"{name}/README.md",
            "content": f"# {name}\n\n{goal}\n\nC++ / CMake scaffold (Visual Studio–friendly).\n\n## Build\n```bash\nmkdir build && cd build\ncmake ..\ncmake --build .\n```\n\nOpen the folder in Visual Studio as a CMake project.\n",
        },
        {
            "path": f"{name}/CMakeLists.txt",
            "content": f"""cmake_minimum_required(VERSION 3.16)
project({name.replace('-', '_')} LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
add_executable(app src/main.cpp src/app.cpp src/app.h)
if(MSVC)
  target_compile_options(app private /W4)
else()
  target_compile_options(app private -Wall -Wextra)
endif()
""",
        },
        {
            "path": f"{name}/src/main.cpp",
            "content": f'''#include "app.h"
#include <iostream>
#include <stdexcept>

int main() {{
    try {{
        App app("{goal[:80]}");
        return app.run();
    }} catch (const std::exception& ex) {{
        std::cerr << "[fatal] " << ex.what() << std::endl;
        // Self-heal hint: capture this message in DreamCoder and request a fix
        return 1;
    }}
}}
''',
        },
        {
            "path": f"{name}/src/app.h",
            "content": '''#pragma once
#include <string>

class App {
public:
    explicit App(std::string goal);
    int run();
private:
    std::string goal_;
    void draw_form_stub();  // placeholder for GUI forms (Qt/Win32/etc.)
    void validate() const;
};
''',
        },
        {
            "path": f"{name}/src/app.cpp",
            "content": f'''#include "app.h"
#include <iostream>
#include <stdexcept>

App::App(std::string goal) : goal_(std::move(goal)) {{}}

void App::validate() const {{
    if (goal_.empty()) throw std::invalid_argument("goal required");
}}

void App::draw_form_stub() {{
    // Hypothetical forms surface – replace with Qt, wx, or Win32 dialogs
    std::cout << "==== " << goal_ << " ====\\n";
    std::cout << "[Form] Title: Sample window\\n";
    std::cout << "[Form] Button: OK\\n";
}}

int App::run() {{
    validate();
    draw_form_stub();
    std::cout << "App running. Prompt was related to: {prompt[:60]}\\n";
    return 0;
}}
''',
        },
    ]


def _gen_c(name: str, prompt: str, goal: str) -> list[dict[str, str]]:
    return [
        {
            "path": f"{name}/README.md",
            "content": f"# {name}\n\n{goal}\n\n```bash\nmake\n./app\n```\n",
        },
        {
            "path": f"{name}/Makefile",
            "content": "CC=gcc\nCFLAGS=-Wall -Wextra -std=c11\napp: src/main.c src/app.c\n\t$(CC) $(CFLAGS) -o app src/main.c src/app.c\nclean:\n\trm -f app\n",
        },
        {
            "path": f"{name}/src/main.c",
            "content": f'''#include "app.h"
#include <stdio.h>

int main(void) {{
    int rc = app_run("{goal[:60]}");
    if (rc != 0) {{
        fprintf(stderr, "app failed with code %d\\n", rc);
    }}
    return rc;
}}
''',
        },
        {
            "path": f"{name}/src/app.h",
            "content": "#pragma once\nint app_run(const char *goal);\n",
        },
        {
            "path": f"{name}/src/app.c",
            "content": '''#include "app.h"
#include <stdio.h>
#include <string.h>

int app_run(const char *goal) {
    if (!goal || !goal[0]) {
        fprintf(stderr, "error: empty goal\\n");
        return 1;
    }
    printf("goal: %s\\n", goal);
    return 0;
}
''',
        },
    ]


def _gen_ts(name: str, prompt: str, goal: str) -> list[dict[str, str]]:
    return [
        {
            "path": f"{name}/README.md",
            "content": f"# {name}\n\n{goal}\n\n```bash\nnpm install\nnpm start\n```\n",
        },
        {
            "path": f"{name}/package.json",
            "content": json.dumps(
                {
                    "name": name,
                    "version": "0.1.0",
                    "private": True,
                    "scripts": {"start": "node dist/index.js", "build": "tsc"},
                    "devDependencies": {"typescript": "^5.6.0"},
                },
                indent=2,
            )
            + "\n",
        },
        {
            "path": f"{name}/tsconfig.json",
            "content": json.dumps(
                {"compilerOptions": {"outDir": "dist", "strict": True, "target": "ES2020", "module": "commonjs"}, "include": ["src"]},
                indent=2,
            )
            + "\n",
        },
        {
            "path": f"{name}/src/index.ts",
            "content": f'''export class App {{
  constructor(private goal: string) {{}}
  run(): void {{
    if (!this.goal.trim()) throw new Error("goal required");
    console.log(`Running: ${{this.goal}}`);
  }}
}}

new App({goal!r}).run();
''',
        },
    ]


def _gen_html(name: str, prompt: str, goal: str) -> list[dict[str, str]]:
    return [
        {
            "path": f"{name}/index.html",
            "content": f'''<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>{name}</title>
  <link rel="stylesheet" href="styles.css" />
</head>
<body>
  <header><h1>{name}</h1><p>{goal}</p></header>
  <main id="app"><p>Generated page. Edit freely.</p></main>
  <script src="app.js"></script>
</body>
</html>
''',
        },
        {
            "path": f"{name}/styles.css",
            "content": "body{font-family:system-ui;margin:2rem;background:#0b0e14;color:#e8ecf3}header{margin-bottom:1.5rem}h1{margin:0 0 .5rem}\n",
        },
        {
            "path": f"{name}/app.js",
            "content": "console.log('app ready');\ndocument.getElementById('app').insertAdjacentHTML('beforeend','<p>JS loaded.</p>');\n",
        },
        {
            "path": f"{name}/README.md",
            "content": f"# {name}\n\nOpen `index.html` in a browser.\n\n{goal}\n",
        },
    ]


def _gen_csharp(name: str, prompt: str, goal: str) -> list[dict[str, str]]:
    proj = name.replace("-", "_")
    return [
        {
            "path": f"{name}/README.md",
            "content": f"# {name}\n\n{goal}\n\n```bash\ndotnet run --project {proj}\n```\n",
        },
        {
            "path": f"{name}/{proj}/{proj}.csproj",
            "content": """<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>
""",
        },
        {
            "path": f"{name}/{proj}/Program.cs",
            "content": f'''using System;

var goal = "{goal[:80]}";
if (string.IsNullOrWhiteSpace(goal))
    throw new ArgumentException("goal required");

Console.WriteLine($"App: {{goal}}");
// WinForms/WPF can replace this console stub page-by-page.
''',
        },
    ]


def _gen_rust(name: str, prompt: str, goal: str) -> list[dict[str, str]]:
    return [
        {
            "path": f"{name}/Cargo.toml",
            "content": f'[package]\nname = "{name.replace("-", "_")}"\nversion = "0.1.0"\nedition = "2021"\n',
        },
        {
            "path": f"{name}/src/main.rs",
            "content": f'''fn main() {{
    let goal = "{goal[:80]}";
    if goal.is_empty() {{
        panic!("goal required");
    }}
    println!("goal: {{goal}}");
}}
''',
        },
        {"path": f"{name}/README.md", "content": f"# {name}\n\n```bash\ncargo run\n```\n\n{goal}\n"},
    ]


def _gen_go(name: str, prompt: str, goal: str) -> list[dict[str, str]]:
    return [
        {
            "path": f"{name}/go.mod",
            "content": f"module {name}\n\ngo 1.22\n",
        },
        {
            "path": f"{name}/main.go",
            "content": f'''package main

import (
    "fmt"
    "log"
)

func main() {{
    goal := "{goal[:80]}"
    if goal == "" {{
        log.fatal("goal required")
    }}
    fmt.Println("goal:", goal)
}}
''',
        },
        {"path": f"{name}/README.md", "content": f"# {name}\n\n```bash\ngo run .\n```\n\n{goal}\n"},
    ]


def _gen_java(name: str, prompt: str, goal: str) -> list[dict[str, str]]:
    pkg = name.replace("-", "")
    return [
        {
            "path": f"{name}/README.md",
            "content": f"# {name}\n\n{goal}\n\n```bash\njavac src/Main.java && java -cp src Main\n```\n",
        },
        {
            "path": f"{name}/src/Main.java",
            "content": f'''public class Main {{
    public static void main(String[] args) {{
        String goal = "{goal[:80]}";
        if (goal == null || goal.isBlank()) {{
            throw new IllegalArgumentException("goal required");
        }}
        System.out.println("goal: " + goal);
    }}
}}
''',
        },
    ]


def self_heal(
    error_text: str,
    files: list[dict[str, str]],
    language: str = "python",
) -> dict[str, Any]:
    """Propose fixed file versions given an error message."""
    start = time.perf_counter()
    err = (error_text or "").lower()
    patches: list[dict[str, str]] = []
    reasons: list[str] = []

    for f in files:
        path = f.get("path") or ""
        content = f.get("content") or ""
        new_content = content
        changed = False

        if "modulenotfounderror" in err or "cannot find module" in err:
            if path.endswith("requirements.txt") and "fastapi" in err:
                if "fastapi" not in content:
                    new_content = content + "fastapi>=0.115.0\n"
                    changed = True
                    reasons.append("Added missing dependency to requirements.txt")
        if "syntaxerror" in err or "expected" in err:
            if language == "python" and path.endswith(".py"):
                # ensure final newline
                if not content.endswith("\n"):
                    new_content = content + "\n"
                    changed = True
                    reasons.append(f"Normalized trailing newline in {path}")
        if "undefined reference" in err or "unresolved external" in err:
            if path.endswith(".cpp") or path.endswith(".c"):
                reasons.append(f"Link error – check {path} is listed in the build file")
        if "goal" in err and "empty" in err:
            reasons.append("Validation rejected empty goal – pass a non-empty project goal")

        if changed:
            patches.append({"path": path, "content": new_content, "action": "replace"})

    if not patches and not reasons:
        reasons.append(
            "No automatic patch pattern matched. Share the full error + language for a deeper fix, "
            "or open the failing file and request Suggest / Evolve."
        )
        # Provide a generic debug wrapper suggestion
        if language == "python":
            patches.append(
                {
                    "path": "debug_wrapper.py",
                    "content": (
                        "import traceback\n"
                        "try:\n"
                        "    import main\n"
                        "    main.main()\n"
                        "except Exception:\n"
                        "    traceback.print_exc()\n"
                    ),
                    "action": "create",
                }
            )
            reasons.append("Added debug_wrapper.py to capture full stack traces")

    return {
        "patches": patches,
        "reasons": reasons,
        "error_excerpt": error_text[:500],
        "latency_ms": int((time.perf_counter() - start) * 1000) + 20,
        "ok": bool(patches) or bool(reasons),
    }


def files_to_zip(files: list[dict[str, str]]) -> bytes:
    buf = BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as z:
        for f in files:
            path = f.get("path") or "file.txt"
            content = f.get("content") or ""
            z.writestr(path, content)
    return buf.getvalue()


FILE_BLOCK_RE = re.compile(r"===FILE:\s*(.+?)===\n(.*?)\n===END===", re.DOTALL)
GENERATOR_SYSTEM_PROMPT = """You are an app generator. When asked to build an app, respond ONLY with a sequence of file blocks in this exact format:
===FILE: path/to/file.py===
<file contents>
===END===
Rules:
- No prose, no markdown fences.
- Include every file the app needs: entry point, requirements.txt, templates, static assets.
- The app must run with: pip install -r requirements.txt && python main.py (adjust for the chosen stack).
- Do not invent dependencies you can't verify.
"""

async def generate_project_with_model(prompt: str, project_goal: str, router) -> dict[str, Any]:
    full_prompt=(f"{GENERATOR_SYSTEM_PROMPT}\n\nProject goal: {project_goal or '(none)'}\nUser request:\n{prompt}\n\nOutput all files now.")
    result=await router.recommend(model_name="",prompt=full_prompt,expected_format="file_blocks")
    if not result.get("ok"):
        return {"ok":False,"source":"model","error":result.get("error"),"losers":result.get("losers",[])}
    files=[]
    for match in FILE_BLOCK_RE.finditer(result.get("content","")):
        rel=match.group(1).strip(); body=match.group(2)
        if rel.startswith("..") or Path(rel).is_absolute(): continue
        files.append({"path":rel,"content":body})
    if not files: return {"ok":False,"source":"model","error":"Model produced no valid file blocks"}
    stack=_detect_stack(prompt); name=_slug(prompt)
    return {"ok":True,"source":"model","files":files,"name":name,"stack":stack,"file_count":len(files),
            "summary":f"Model generated {len(files)}-file {stack['language']} project '{name}' via {result.get('winning_lane')}",
            "run_hint":_run_hint(stack,name),"model":result.get("model"),"winning_lane":result.get("winning_lane"),
            "latency_ms":result.get("duration_ms",0),"losers":result.get("losers",[])}
