"""Hugging Face Inference / transformers adapter (stub + light path).

For production you can either:
1. Call the HF Inference API (needs HF_TOKEN)
2. Load a local transformers model (needs GPU + lots of RAM)

This file provides a clean interface; the heavy lifting is left as
optional so the rest of the system stays lightweight.
"""

from __future__ import annotations

import os
import time
from typing import Any, Optional

from .base import BaseModel, ChatContext, ChatResult, CodeContext, InferenceResult, Suggestion
try:
    from provider_runtime import runtime as provider_runtime
except Exception:
    provider_runtime=None
try:
    from quota_tracker import record_response as _record_quota
except Exception:
    def _record_quota(headers, status): pass


class HuggingFaceModel(BaseModel):
    name = "HuggingFace"
    supports_streaming = False

    def __init__(
        self,
        model_id: str = "meta-llama/Llama-3.1-8B-Instruct",
        use_api: bool = True,
        api_token: Optional[str] = None,
    ):
        self.model_id = model_id
        self.use_api = use_api
        self.api_token = api_token or os.getenv("HF_TOKEN")
        self._pipeline = None  # lazy-loaded local pipeline

    async def complete(self, context: CodeContext) -> InferenceResult:
        start = time.perf_counter()

        if self.use_api and self.api_token:
            return await self._via_api(context, start)
        else:
            return InferenceResult(
                suggestions=[],
                latency_ms=int((time.perf_counter() - start) * 1000),
                model=f"HuggingFace/{self.model_id}",
                cached=False,
                health={"status": "token-missing", "backend": "huggingface", "model_id": self.model_id},
            )

    async def _via_api(self, context: CodeContext, start: float) -> InferenceResult:
        import httpx

        prompt = self._build_prompt(context)
        headers = {"Authorization": f"Bearer {self.api_token}"}
        payload = {
            "inputs": prompt,
            "parameters": {
                "max_new_tokens": 400,
                "temperature": 0.2,
                "return_full_text": False,
            },
        }

        try:
            async with httpx.AsyncClient(timeout=90.0) as client:
                resp = await client.post(
                    f"https://api-inference.huggingface.co/models/{self.model_id}",
                    headers=headers,
                    json=payload,
                )
                _record_quota(dict(resp.headers), resp.status_code)
                resp.raise_for_status()
                data = resp.json()
                raw = data[0]["generated_text"] if isinstance(data, list) else str(data)
        except Exception as exc:
            return InferenceResult(
                suggestions=[],
                latency_ms=int((time.perf_counter() - start) * 1000),
                model=f"HuggingFace/{self.model_id}",
                cached=False,
                health={"status": "error", "backend": "huggingface-api", "model_id": self.model_id, "error": str(exc)},
            )

        suggestions = [
            Suggestion(
                id="hf-0",
                title="Model suggestion",
                description="Generated by Hugging Face Inference API",
                code=raw[:800],
                category="improvement",
                confidence=0.82,
            )
        ]
        latency = int((time.perf_counter() - start) * 1000)
        return InferenceResult(
            suggestions=suggestions,
            latency_ms=latency,
            model=f"HuggingFace/{self.model_id}",
            cached=False,
            architecture_insights=[
                {
                    "icon": "🤗",
                    "title": "Hugging Face Inference",
                    "detail": f"Using {self.model_id}",
                }
            ],
            health={"score": 88, "backend": "huggingface-api"},
        )

    async def chat(self, context: ChatContext) -> ChatResult:
        start = time.perf_counter()
        prompt = self._build_chat_prompt(context)
        if context.mode == "analysis" or "Return ONLY" in prompt:
            prompt += "\n\nRespond with raw JSON only. No prose, no markdown fences."
        if not self.api_token:
            return ChatResult(content=f"Selected model HuggingFace/{self.model_id} has no HF_TOKEN configured.", latency_ms=int((time.perf_counter()-start)*1000), model=f"HuggingFace/{self.model_id}", backend="huggingface")
        try:
            import httpx
            async with httpx.AsyncClient(timeout=90.0) as client:
                resp = await client.post(
                    f"https://api-inference.huggingface.co/models/{self.model_id}",
                    headers={"Authorization": f"Bearer {self.api_token}"},
                    json={"inputs": prompt, "parameters": {"max_new_tokens": 1200, "temperature": 0.3, "return_full_text": False}},
                )
                _record_quota(dict(resp.headers), resp.status_code)
                resp.raise_for_status()
                data = resp.json()
                raw = data[0].get("generated_text", "") if isinstance(data, list) else str(data)
                return ChatResult(content=raw.strip() or "(empty model response)", latency_ms=int((time.perf_counter()-start)*1000), model=f"HuggingFace/{self.model_id}", backend="huggingface")
        except Exception as exc:
            return ChatResult(content=f"Selected model HuggingFace/{self.model_id} is unavailable: {exc}", latency_ms=int((time.perf_counter()-start)*1000), model=f"HuggingFace/{self.model_id}", backend="huggingface")

    def _build_chat_prompt(self, context: ChatContext) -> str:
        project = ""
        if context.project_context:
            project = f"\\nProject goal: {context.project_goal}\\nProject context:\\n{context.project_context}\\n"
        history = "\\n".join(f"{m.get('role','user')}: {m.get('content','')}" for m in context.history[-8:])
        return f"You are the selected DreamCoder assistant. Answer directly and honestly. Do not claim actions you did not perform.{project}\\nConversation:\\n{history}\\nuser: {context.message}\\nassistant:"

    async def health_check(self) -> dict[str, Any]:
        return {
            "status": "configured" if self.api_token else "token-missing",
            "model_id": self.model_id,
            "mode": "api" if self.use_api else "local",
            "has_token": bool(self.api_token),
        }

    def _build_prompt(self, ctx: CodeContext) -> str:
        return (
            f"### Instruction:\n"
            f"Suggest concrete code improvements for the following {ctx.language} snippet.\n"
            f"Return short, actionable suggestions with code.\n\n"
            f"### Code:\n{ctx.code}\n\n"
            f"### Response:\n"
        )


    async def stream_chat(self, context: ChatContext):
        import httpx,json
        prompt=self._build_chat_prompt(context)
        headers={"Authorization":f"Bearer {self.api_token}","Accept":"text/event-stream"}
        async with httpx.AsyncClient(timeout=90.0) as client:
            async with client.stream("POST",f"https://api-inference.huggingface.co/models/{self.model_id}",headers=headers,json={"inputs":prompt,"parameters":{"max_new_tokens":1200,"temperature":0.3},"stream":True}) as resp:
                _record_quota(dict(resp.headers),resp.status_code); resp.raise_for_status()
                async for line in resp.aiter_lines():
                    if not line or not line.startswith("data:"): continue
                    payload=line[5:].strip()
                    if payload=="[DONE]": break
                    try:
                        data=json.loads(payload)
                        token=data.get("token",{}).get("text") if isinstance(data,dict) else None
                        if token:\n                            if provider_runtime: provider_runtime.record_usage("huggingface:"+self.model_id,0,max(1,len(token.split())))\n                            yield token
                        elif isinstance(data,dict) and data.get("generated_text"): yield data["generated_text"]
                    except Exception: continue

    def _build_chat_prompt(self, context: ChatContext):
        return "You are the DreamCoder coding assistant. Answer directly.\n"+context.message
